import { ConnectButton } from '@rainbow-me/rainbowkit';
import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import { abi } from '../../data.json';
import { useReadContract } from 'wagmi'
import { useState } from 'react';

const Home: NextPage = () => {
  const [votingStatus, setVotingStatus] = useState(true);
  const [remainingTime, setRemainingTime] = useState(0);
  const [candidates, setCandidates] = useState([]);
  const [number, setNumber] = useState('');
  const [CanVote, setCanVote] = useState(true);

  const getVotingStatus = () => {
    const { data } = useReadContract({
      abi,
      address: '0x4C157380A7FC150c7258c4E5C0DDAf480b329E5B',
      functionName: 'getVotingStatus',
    })

    setVotingStatus(data as boolean);
  }

  const getRemaningTime = () => {
    const { data } = useReadContract({
      abi,
      address: '0x4C157380A7FC150c7258c4E5C0DDAf480b329E5B',
      functionName: 'getRemainingTime',
    })

    setRemainingTime(parseInt(data as string, 16));
  }

  const getCandidates = () => {
    const { data } = useReadContract({
      abi,
      address: '0x4C157380A7FC150c7258c4E5C0DDAf480b329E5B',
      functionName: 'getRemainingTime',
    })
  }
  


  return (
    <div className={styles.container}>
      <Head>
        <title>RainbowKit App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <ConnectButton />
      </main>

      <footer className={styles.footer}>
        <a href="https://rainbow.me" rel="noopener noreferrer" target="_blank">
          Made with ❤️ by your frens at 🌈
        </a>
      </footer>
    </div>
  );
};

export default Home;
